<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UseVSTest>true</UseVSTest>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../src/MachiVerseWorks.Server/MachiVerseWorks.Server.csproj" />
  </ItemGroup>
</Project>
