namespace MachiVerseWorks.Protocol;

public enum MessageType : ushort
{
    Hello = 1,
    HelloAck = 2,
    SubscribeVolume = 3,
    InspectPerson = 4,
    ClearPersonInspection = 5,
    InspectEntity = 6,
    ClearEntityInspection = 7,
    AgentSpawn = 100,
    AgentUpdate = 101,
    AgentRemove = 102,
    RoadNetworkSnapshot = 200,
    PedestrianSpawn = 300,
    PedestrianUpdate = 301,
    PedestrianRemove = 302,
    VehicleSpawn = 400,
    VehicleUpdate = 401,
    VehicleRemove = 402,
    IntersectionControlSnapshot = 500,
    PopulationStatistics = 600,
    PersonDebug = 601,
    RailwayInfrastructureSnapshot = 700,
    RailwayOperationsSnapshot = 710,
    MultimodalTransitSnapshot = 720,
    MultimodalTransitSnapshotChunk = 721,
    EconomySnapshot = 730,
    LogisticsSnapshot = 740,
    PowerSnapshot = 750,
    WaterSewerSnapshot = 760,
    GasSnapshot = 770,
    OpticalSnapshot = 780,
    RadioSnapshot = 790,
    SpectrumSnapshot = 791,
    WorldEnvironmentSnapshot = 800,
    RegionalGenerationSnapshot = 810,
    RegionalGenerationSnapshotChunk = 811,
    PersistentRegionalEvolutionSnapshot = 820,
    EntityInspectionSnapshot = 830,
    Error = 900,
}
