<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UseVSTest>true</UseVSTest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/persistence/MachiVerseWorks.Persistence.csproj" />
    <ProjectReference Include="../../src/protocol/MachiVerseWorks.Protocol.csproj" />
    <ProjectReference Include="../../src/simulation/MachiVerseWorks.Simulation.csproj" />
  </ItemGroup>
</Project>
